package OperationsAppTasks;

import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.logging.LogType;
import org.openqa.selenium.logging.LoggingPreferences;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;
import org.testng.Reporter;
import org.testng.annotations.Test;

import com.pittsburgh.base.Baseclass;

public class Task1828POSModule {
	public static WebDriver driver;
	public static Properties p1;
//Testcase-1
	@Test(priority = 1, enabled=true)
	public void Createanorderwithpickedproducts() throws IOException, Exception {
		String	Testname="Createanorderwithpickedproducts";
//		System.setProperty("webdriver.chrome.driver","./Lib/Browsers/chromedriver.exe");	
		Baseclass.setup();
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--disable-notifications");
		driver = new ChromeDriver(options);
		FileInputStream fis = new FileInputStream("./Lib/Properties/PropertyFile");
		p1 = new Properties();
		p1.load(fis);
	//	driver.get(p1.getProperty("URL"));
		DesiredCapabilities cap = DesiredCapabilities.chrome();
        cap.setCapability(ChromeOptions.CAPABILITY, options);
		 LoggingPreferences logPrefs = new LoggingPreferences();
         logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
         options.setCapability("goog:loggingPrefs", logPrefs);
         driver.get(p1.getProperty("URL"));
		driver.manage().window().maximize();
		// driver.switchTo().alert().accept();
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		driver.findElement(By.xpath("//*[text()='Login']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@placeholder='Email']")).sendKeys(p1.getProperty("Username"));
		driver.findElement(By.xpath("//input[@placeholder='Password']")).sendKeys(p1.getProperty("Password"));
		driver.findElement(By.xpath("//ion-button[@type='submit']")).click();
		String pagetitle = driver.getTitle();
		System.out.println(pagetitle);
		Thread.sleep(5000);//*[@id="mat-expansion-panel-header-5"]/span[1]/mat-panel-title
		driver.findElement(By.xpath("//*[@id=\"mat-expansion-panel-header-5\"]/span[1]/mat-panel-title")).click();
		//driver.findElement(By.xpath("//*[text()=' View ']")).click();
		Thread.sleep(3000);
	    WebElement clickonview= driver.findElement(By.xpath("//*[text()=' View ']"));
		JavascriptExecutor moveuptoview = (JavascriptExecutor) driver;
		moveuptoview.executeScript("arguments[0].click();", clickonview);
		driver.findElement(By.xpath("//*[@id='mat-dialog-0']/app-pos-view-screen/div/ion-button[3]")).click();
		Thread.sleep(3000);
		WebElement Okay=driver.findElement(By.xpath("//*[text()='Okay']"));
		boolean b=Okay.isDisplayed();
		System.out.println("Boolean  : "+b);
		if (b==true) {
			Okay.click();
			System.out.println("True________"+b+"______Clicked");
		}
		else {
			System.out.println("If failed");
		}
		WebElement PosName=driver.findElement(By.xpath("//*[@class=\'form-control ng-untouched ng-pristine ng-invalid\']"));
		PosName.click();
		PosName.sendKeys("sardar");
		driver.findElement(By.xpath("//*[@type='Submit']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Start New Order']")).click();
		Reporter.log("Clicked on Started New Order");
		driver.findElement(By.xpath("//*[text()='Search For Customer']")).click();
		driver.findElement(By.xpath("//*[@id='form-group-input-1']")).sendKeys("sardar");
		driver.findElement(By.xpath("//*[@type='submit']")).click();
		Thread.sleep(3000);
		//driver.findElement(By.xpath("(//tr[@class='mat-row ng-star-inserted'])[1]")).click();
	    WebElement clickoncustomer= driver.findElement(By.xpath("(//tr[@class='mat-row ng-star-inserted'])[5]"));
			JavascriptExecutor moveuptocustomer = (JavascriptExecutor) driver;
			moveuptocustomer.executeScript("arguments[0].click();", clickoncustomer);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//ion-button[text()='Yes']")).click();
		Thread.sleep(3000);
	//	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-search-customer/ion-content/ion-card[3]/ion-card-content/table/tbody/tr/td[1]")).click();
	    WebElement clickoncustomerorganization= driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-search-customer/ion-content/ion-card[3]/ion-card-content/table/tbody/tr/td[1]"));
			JavascriptExecutor moveuptocustomerorganization = (JavascriptExecutor) driver;
			moveuptocustomerorganization.executeScript("arguments[0].click();", clickoncustomerorganization);
		Thread.sleep(5000);
		driver.findElement(By.xpath("//*[text()='Yes']")).click();
		Thread.sleep(3000);
		//driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-verify-organization/ion-content/ion-card[2]/ion-card-content/div/div[1]/ion-button")).click();
		WebElement clickonskip= driver.findElement(By.xpath("//*[text()='Skip']"));
		JavascriptExecutor moveuptoskip = (JavascriptExecutor) driver;
		moveuptoskip.executeScript("arguments[0].click();", clickonskip);
		Thread.sleep(3000);
		WebElement clickpaymentordertype= driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-verify-organization/ion-content/ion-card[2]/ion-card-content/div/div[1]/ion-button"));
		JavascriptExecutor moveuptopaymentordertype = (JavascriptExecutor) driver;
		moveuptopaymentordertype.executeScript("arguments[0].click();", clickpaymentordertype);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//ion-button[text()='OK']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("(//ion-icon[@aria-label='create'])[4]")).click();
	     Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Neville Island']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Pick BIN Label ']")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("//*[@id=\"mat-dialog-3\"]/app-print-dialog/div/button[1]/span/div[1]")).click();
	WebElement clickonprinter= driver.findElement(By.xpath("//*[text()='Microsoft Print to PDF']"));
	JavascriptExecutor moveuptoprinter = (JavascriptExecutor) driver;
	moveuptoprinter.executeScript("arguments[0].click();", clickonprinter);
	Thread.sleep(5000);
	driver.findElement(By.xpath("//*[text()='Print ']")).click();
	Thread.sleep(3000);
	WebElement hiddenDivtag = driver.findElement(By.xpath("//span[@name='pickBinLabel']"));
	String nnn = hiddenDivtag.getText(); // does not work (returns "" as expected)
	String scripttt = "return arguments[0].innerText";
	nnn= (String) ((JavascriptExecutor) driver).executeScript(scripttt, hiddenDivtag);
	System.out.println(nnn);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Add Pants']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//div[@class='mat-radio-container'])[1]")).click();
	driver.findElement(By.xpath("(//ion-button[@color='success'])[6]")).click();
	driver.findElement(By.xpath("//input[@type='number']")).sendKeys("12");
	driver.findElement(By.xpath("//span[text()='Ok']")).click();
	WebElement hiddenDiv = driver.findElement(By.xpath("//span[@name='ppssBarcode']"));
	String n = hiddenDiv.getText(); // does not work (returns "" as expected)
	String script = "return arguments[0].innerText";
	n= (String) ((JavascriptExecutor) driver).executeScript(script, hiddenDiv);
	System.out.println(n);
	driver.findElement(By.xpath("//input[@name='upc']")).sendKeys(n);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//input[@name='upc']")).sendKeys(nnn);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();   
	}
@Test(priority=2,enabled=true)
public void testAddproductmodule() throws Exception
{
	Thread.sleep(3000);
	WebElement addproduct=driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproductt = (JavascriptExecutor) driver;
	moveuptoaddproductt.executeScript("arguments[0].scrollIntoView();", addproduct);
	Thread.sleep(3000);
    WebElement clickonaddproduct= driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproduct = (JavascriptExecutor) driver;
	moveuptoaddproduct.executeScript("arguments[0].click();", clickonaddproduct);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Search Product to Add']")).click(); 
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//div[@class='custom-select'])[1]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()=' 5.11 Tactical ']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//div[@class='custom-select'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()=' 10011 ']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@type='submit'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//td[text()=' 5.11 Tactical ']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Show Related ']")).click();
	Thread.sleep(3000);
//	driver.findElement(By.xpath("(//*[text()=' FOLIAGE '])[1]")).click();
	WebElement clickonproduct1= driver.findElement(By.xpath("(//*[text()=' FOLIAGE '])[1]"));
	JavascriptExecutor moveuptoproduct1 = (JavascriptExecutor) driver;
	moveuptoproduct1.executeScript("arguments[0].click();", clickonproduct1);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[text()=' Add product to Order'])[1]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@color='success'])[6]")).click();
}
@Test(priority=3,enabled=true)
public void testAddshirtmodule() throws Exception
{
	Thread.sleep(3000);
	WebElement addproduct=driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproductt = (JavascriptExecutor) driver;
	moveuptoaddproductt.executeScript("arguments[0].scrollIntoView();", addproduct);
	Thread.sleep(3000);
    WebElement clickonaddshirt= driver.findElement(By.xpath("//*[text()='Add Shirt']"));
	JavascriptExecutor moveuptoaddshirt = (JavascriptExecutor) driver;
	moveuptoaddshirt.executeScript("arguments[0].click();", clickonaddshirt);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@color='success'])[6]")).click();
}
@Test(priority=4,enabled=true)
public void Testmodule() throws Exception
{
	Thread.sleep(5000);
	WebElement addproduct=driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproductt = (JavascriptExecutor) driver;
	moveuptoaddproductt.executeScript("arguments[0].scrollIntoView();", addproduct);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='test']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@color='success'])[6]")).click();
}
@Test(priority=5,enabled=true)
public void testFlashlightmodule() throws Exception
{
	Thread.sleep(5000);
	WebElement addproduct=driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproductt = (JavascriptExecutor) driver;
	moveuptoaddproductt.executeScript("arguments[0].scrollIntoView();", addproduct);
	Thread.sleep(3000);
//	driver.findElement(By.xpath("//*[text()='Add Flashlight']")).click();
	WebElement clickonflashlight=driver.findElement(By.xpath("//*[text()='Add Flashlight']"));
	JavascriptExecutor moveuptoflashlight = (JavascriptExecutor) driver;
	moveuptoflashlight.executeScript("arguments[0].click();", clickonflashlight);
	Thread.sleep(5000);
	//driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]")).click();
	WebElement droptocustomerbutton=driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]"));
	JavascriptExecutor moveuptodropcustomer = (JavascriptExecutor) driver;
	moveuptodropcustomer.executeScript("arguments[0].click();", droptocustomerbutton);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@color='success'])[6]")).click();
}
@Test(priority=6,enabled=true)
public void Testcustomization() throws Exception
{
	Thread.sleep(5000);
//	driver.findElement(By.xpath("(//*[@class='product'])[1]")).click();
	WebElement select1stone=driver.findElement(By.xpath("(//*[@class='product'])[4]"));
	JavascriptExecutor moveupto1stproduct = (JavascriptExecutor) driver;
	moveupto1stproduct.executeScript("arguments[0].click();", select1stone);
	Thread.sleep(4000);
    driver.findElement(By.xpath("//ion-button[text()='Customization']")).click();
    Thread.sleep(3000);
    driver.findElement(By.xpath("//ion-button[text()='Alteration']")).click();
    Thread.sleep(3000);
 WebElement alterationdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='alterationType']"));
 Select selectalterationdropdown=new Select(alterationdropdown);
 selectalterationdropdown.selectByVisibleText("Add Patch");
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[1]")).click();
 Thread.sleep(3000);
 WebElement patchdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='patchLocation']"));
 Select selectpatchdropdown=new Select(patchdropdown);
 selectpatchdropdown.selectByVisibleText("Left Shoulder");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[2]")).click();
 Thread.sleep(3000);
 WebElement clientpatchdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='patchType']"));
 Select selectclientpatchdropdown=new Select(clientpatchdropdown);
 selectclientpatchdropdown.selectByVisibleText("Client Patch");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[3]")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='embellishmentName']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()=' UPMC Police Emblem - ( CP000000012 ) ']")).click();
 Thread.sleep(3000);
// driver.findElement(By.xpath("(//ion-button[text()='Next'])[4]")).click();
 WebElement clickon4thnextbutton=driver.findElement(By.xpath("(//ion-button[text()='Next'])[4]"));
	JavascriptExecutor moveupto4thnextbutton= (JavascriptExecutor) driver;
	moveupto4thnextbutton.executeScript("arguments[0].click();", clickon4thnextbutton);
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='notes']")).sendKeys("test");
 Thread.sleep(3000);
 driver.findElement(By.xpath("//ion-button[text()='Finish']")).click();
 driver.findElement(By.xpath("//ion-button[text()=' Embroidery']")).click();
 Thread.sleep(3000);
 WebElement Embroiderylocdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='embroideryLocation']"));
 Select selectEmbroiderylocdropdown=new Select(Embroiderylocdropdown);
 selectEmbroiderylocdropdown.selectByVisibleText("Left Chest");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[1]")).click();
 Thread.sleep(3000);
 WebElement Embroiderytypedropdown=   driver.findElement(By.xpath("//select[@formcontrolname='embroideryType']"));
 Select selectEmbroiderytypedropdown=new Select(Embroiderytypedropdown);
 selectEmbroiderytypedropdown.selectByVisibleText("Client Embroidery");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[2]")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='embellishmentName']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()=' UPMC POLICE - ( EMB000000145 ) '] ")).click();
// driver.findElement(By.xpath("(//ion-button[text()='Next'])[3]")).click();
 WebElement clickon3rdthnextbutton=driver.findElement(By.xpath("(//ion-button[text()='Next'])[3]"));
	JavascriptExecutor moveupto3rdthnextbutton= (JavascriptExecutor) driver;
	moveupto3rdthnextbutton.executeScript("arguments[0].click();", clickon3rdthnextbutton);
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='notes']")).sendKeys("test");
 driver.findElement(By.xpath("//ion-button[text()='Finish']")).click();
//    driver.findElement(By.xpath("//ion-button[text()='Finish']")).click();
//   driver.findElement(By.xpath("//ion-button[text()=' Embroidery']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//ion-button[text()='Print']")).click();
 WebElement printlocdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='patchLocation']"));
 Select selectprintlocdropdown=new Select(printlocdropdown);
 selectprintlocdropdown.selectByVisibleText("Both Shoulders");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[1]")).click();
 Thread.sleep(3000);
 WebElement printtypedropdown=   driver.findElement(By.xpath("//select[@formcontrolname='printType']"));
 Select selectprinttypedropdown=new Select(printtypedropdown);
 selectprinttypedropdown.selectByVisibleText("Client Print");// done
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[2]")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='embellishmentName']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()=' Client Print test - ( CPR000000002 ) ']")).click();
 Thread.sleep(3000);
 WebElement elementt= driver.findElement(By.xpath("(//ion-button[text()='Next'])[3]"));
 JavascriptExecutor jss = (JavascriptExecutor) driver;
 jss.executeScript("arguments[0].click();", elementt);
//   driver.findElement(By.xpath("(//ion-button[text()='Next'])[3]")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='notes']")).sendKeys("test");
 driver.findElement(By.xpath("//ion-button[text()='Finish']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//ion-button[text()='Vinyl']")).click();
 WebElement vinyllocdropdown=   driver.findElement(By.xpath("//select[@formcontrolname='patchLocation']"));
 Select selectvinyllocdropdown=new Select(vinyllocdropdown);
 selectvinyllocdropdown.selectByVisibleText("Both Shoulders");
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[1]")).click();
 Thread.sleep(3000);
 WebElement vinyltypedropdown=   driver.findElement(By.xpath("//select[@formcontrolname='printType']"));
 Select selectvinyltypedropdown=new Select(vinyltypedropdown);
 selectvinyltypedropdown.selectByVisibleText("Client Vinyl");// done
 Thread.sleep(3000);
 driver.findElement(By.xpath("(//ion-button[text()='Next'])[2]")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//input[@formcontrolname='embellishmentName']")).click();
 Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()=' Vinyl Design 1 New - ( CV000000004 ) ']")).click();
 Thread.sleep(6000);
 driver.findElement(By.xpath("(//*[text()='Next'])[3]")).click();
/* Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()='Upload Image']")).click();
 Thread.sleep(2000);
	StringSelection ss = new StringSelection("C:\\Users\\ss21056\\Downloads\\Ce que j'aime de l'automne -  Natureimage B.jpg");
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
    Robot robot = new Robot();
    Thread.sleep(2000);
    robot.keyPress(KeyEvent.VK_ENTER);
    robot.keyRelease(KeyEvent.VK_ENTER);
    robot.keyPress(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_V);
    robot.keyRelease(KeyEvent.VK_V);
    robot.keyRelease(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_ENTER);
    Thread.sleep(2000);
    robot.keyRelease(KeyEvent.VK_ENTER);
    Thread.sleep(3000);
    driver.findElement(By.xpath("//*[@placeholder='Print Name']")).sendKeys("testing");
    Thread.sleep(3000);
    driver.findElement(By.xpath("//*[text()='Ok']")).click();
    Thread.sleep(6000);
    driver.findElement(By.xpath("//ion-button[text()='Next ']")).click();
    Thread.sleep(6000);
    driver.findElement(By.xpath("//*[@placeholder='Print Name']")).sendKeys("testing");
    Thread.sleep(3000);
    driver.findElement(By.xpath("//*[text()='Ok']")).click();    */
    Thread.sleep(3000);
   // driver.findElement(By.xpath("(//*[text()='Cancel'])")).click();
    WebElement clickoncancelbbutton=driver.findElement(By.xpath("(//*[text()='Cancel'])"));
   	JavascriptExecutor moveuptocancel= (JavascriptExecutor) driver;
   	moveuptocancel.executeScript("arguments[0].click();", clickoncancelbbutton);
 Thread.sleep(3000);
 driver.findElement(By.xpath("//*[text()='Done']")).click();
 Thread.sleep(3000);
 WebElement selectproduct2ndtime=driver.findElement(By.xpath("(//*[@class='product'])[4]"));
	JavascriptExecutor moveuptoproduct2ndtime = (JavascriptExecutor) driver;
	moveuptoproduct2ndtime.executeScript("arguments[0].click();", selectproduct2ndtime);
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[@class='slider round']")).click();
	 Thread.sleep(3000);
	 WebElement taxpurposedropdown=   driver.findElement(By.xpath("//select[@class='form-control custom-select ng-untouched ng-pristine ng-valid']"));
	 Select selecttaxpurposedropdown=new Select(taxpurposedropdown);
	 selecttaxpurposedropdown.selectByVisibleText("test123");
	 Thread.sleep(5000);
	// driver.findElement(By.xpath("(//*[@class='mat-radio-outer-circle'])[3]")).click();
	 WebElement select3rdradiobutton=driver.findElement(By.xpath("(//*[@class='mat-radio-outer-circle'])[3]"));
		JavascriptExecutor moveupto3rdradiobutton = (JavascriptExecutor) driver;
		moveupto3rdradiobutton.executeScript("arguments[0].click();", select3rdradiobutton);
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[@aria-label='Open calendar']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='13']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='UPDATE']")).click();
	 Thread.sleep(3000);
	 WebElement scrollupto4thproduct=driver.findElement(By.xpath("(//*[@class='product'])[4]"));
		JavascriptExecutor moveupto4thproducttime = (JavascriptExecutor) driver;
		moveupto4thproducttime.executeScript("arguments[0].scrollIntoView();", scrollupto4thproduct);
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[text()=' + '])[4]")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("//*[text()='Dropship to customer']")).click();
}
@Test(priority=7,enabled=true)
public void testOrderActions() throws Exception
{
	Thread.sleep(5000);
	WebElement addproduct=driver.findElement(By.xpath("//*[text()='Add Product ']"));
	JavascriptExecutor moveuptoaddproductt = (JavascriptExecutor) driver;
	moveuptoaddproductt.executeScript("arguments[0].scrollIntoView();", addproduct);
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()=' Order Actions']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()=' Change Order Type']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Agency Order']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Cancel']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='PO Info']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@type='text'])[7]")).sendKeys("123");
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Save']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Order Notes']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[@data-placeholder='Insert text here ...']")).sendKeys("Doing Testing");
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Ok']")).click();
/*	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Order Discount']")).click();
	 Thread.sleep(3000);
	 WebElement discountdropdown=   driver.findElement(By.xpath("//*[@class='mat-dialog-content']"));
	 Select selectdiscountdropdown=new Select(discountdropdown);
	 selectdiscountdropdown.selectByVisibleText("25%");    
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Ok']")).click();   */
}
@Test(priority=8,enabled=true)
public void testuploaddocument() throws Exception
{
	 Thread.sleep(5000);
	 driver.findElement(By.xpath("//*[text()='Upload Image or Document']")).click();
	 Thread.sleep(2000);
		StringSelection ss = new StringSelection(System.getProperty("fileToUpload"));
	    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
	    Robot robot = new Robot();
	    Thread.sleep(2000);
	    robot.keyPress(KeyEvent.VK_ENTER);
	    robot.keyRelease(KeyEvent.VK_ENTER);
	    robot.keyPress(KeyEvent.VK_CONTROL);
	    robot.keyPress(KeyEvent.VK_V);
	    robot.keyRelease(KeyEvent.VK_V);
	    robot.keyRelease(KeyEvent.VK_CONTROL);
	    robot.keyPress(KeyEvent.VK_ENTER);
	    Thread.sleep(2000);
	    robot.keyRelease(KeyEvent.VK_ENTER);
}

@Test(priority=9,enabled=false)
public void testViewddocuments() throws Exception
{
	Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='VIEW DOCUMENTS']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Search All Document']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[@formcontrolname='document']")).sendKeys("test");
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[text()='Search'])[3]")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@class='mat-row ng-star-inserted'])[1]")).click();
	 Thread.sleep(3000);
		WebElement backbutton=driver.findElement(By.xpath("//*[text()='Back']"));
		JavascriptExecutor moveuptobackproductt = (JavascriptExecutor) driver;
		moveuptobackproductt.executeScript("arguments[0].scrollIntoView();", backbutton);
	 Thread.sleep(3000);
	 WebElement clickonback=driver.findElement(By.xpath("//*[text()='Back']"));
	JavascriptExecutor moveuptobackbutton= (JavascriptExecutor) driver;
	moveuptobackbutton.executeScript("arguments[0].click();", clickonback);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Back']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='User Document']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[text()='Search'])[3]")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@class='mat-row ng-star-inserted'])[1]")).click();
	 Thread.sleep(3000);
	 WebElement secondbackbutton=driver.findElement(By.xpath("//*[text()='Back']"));
		JavascriptExecutor moveuptoback2productt = (JavascriptExecutor) driver;
		moveuptoback2productt.executeScript("arguments[0].scrollIntoView();", secondbackbutton);
	 Thread.sleep(3000);
	 WebElement clickonclose=driver.findElement(By.xpath("//*[text()='Close Details']"));
	JavascriptExecutor moveuptoclosebutton= (JavascriptExecutor) driver;
	moveuptoclosebutton.executeScript("arguments[0].click();", clickonclose);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Back']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Back']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Client Document']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[text()='Search'])[3]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@class='mat-row ng-star-inserted'])[2]")).click();
	 Thread.sleep(3000);
	 WebElement thirdbackbutton=driver.findElement(By.xpath("//*[text()='Back']"));
		JavascriptExecutor moveuptoback3rdproductt = (JavascriptExecutor) driver;
		moveuptoback3rdproductt.executeScript("arguments[0].scrollIntoView();", thirdbackbutton);
	Thread.sleep(3000);
	 WebElement clickon2ndback=driver.findElement(By.xpath("//*[text()='Back']"));
	JavascriptExecutor moveupto2ndbackbutton= (JavascriptExecutor) driver;
	moveupto2ndbackbutton.executeScript("arguments[0].click();", clickon2ndback);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Back']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//div[@class='cdk-overlay-container']")).click();
}
@Test(priority=10,enabled=true)
public void testUserActions() throws Exception
{
	Thread.sleep(3000);
	WebElement selectUseractions=driver.findElement(By.xpath("//*[text()='User Actions ']"));
	JavascriptExecutor moveuptoUserActions = (JavascriptExecutor) driver;
	moveuptoUserActions.executeScript("arguments[0].scrollIntoView();", selectUseractions);
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[text()='Edit'])[1]")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//input[@formcontrolname='firstName']")).clear();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//input[@formcontrolname='firstName']")).sendKeys("Sardar12345");
	 Thread.sleep(3000);
	// driver.findElement(By.xpath("//*[text()='Update']")).click();
	 WebElement clickonupdatebutton=driver.findElement(By.xpath("//*[text()='Update']"));
		JavascriptExecutor moveuptoupdatebutton= (JavascriptExecutor) driver;
		moveuptoupdatebutton.executeScript("arguments[0].click();", clickonupdatebutton);
		Thread.sleep(3000);
		WebElement storeuseractions=driver.findElement(By.xpath("//*[text()='User Actions ']"));
		JavascriptExecutor moveuptoUserActions3 = (JavascriptExecutor) driver;
		moveuptoUserActions3.executeScript("arguments[0].scrollIntoView();", storeuseractions);
		Thread.sleep(3000);
		WebElement storeuseractions4=driver.findElement(By.xpath("//*[text()='User Actions ']"));
		JavascriptExecutor moveuptoUserActions4 = (JavascriptExecutor) driver;
		moveuptoUserActions4.executeScript("arguments[0].click();", storeuseractions4);
		Thread.sleep(3000);
		 driver.findElement(By.xpath("//*[text()='View Authorized Items']")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[text()='Uniform Spec Products'])[1]")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@name='add'])[1]")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[text()=' LS ZIPPERED POLYESTER SHIRT (15/39, dark navy) 8600-Z '])")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[text()='Show Related '])[1]")).click();
		 Thread.sleep(3000);
		 WebElement store1stprooduct=driver.findElement(By.xpath("//*[text()=' BLACK ']"));
			JavascriptExecutor moveupto1stproduct = (JavascriptExecutor) driver;
			moveupto1stproduct.executeScript("arguments[0].click();", store1stprooduct);
			Thread.sleep(3000);
			driver.findElement(By.xpath("(//*[text()=' Add product to Order'])[1]")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[3]")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("(//*[@color='success'])[3]")).click();
		Thread.sleep(3000);
		WebElement select2ndUseractions=driver.findElement(By.xpath("//*[text()='User Actions ']"));
		JavascriptExecutor moveuptoUserActions2 = (JavascriptExecutor) driver;
		moveuptoUserActions2.executeScript("arguments[0].scrollIntoView();", select2ndUseractions);
		 Thread.sleep(3000);
		// driver.findElement(By.xpath("(//*[text()='Edit'])[2]")).click();
		 WebElement select2ndUseractionsedits=driver.findElement(By.xpath("(//*[text()='Edit'])[2]"));
			JavascriptExecutor moveuptoUserActionsedit22 = (JavascriptExecutor) driver;
			moveuptoUserActionsedit22.executeScript("arguments[0].click();", select2ndUseractionsedits);
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("//*[text()='Add New Rank Or Title']")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@type='text'])[1]")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@role='checkbox'])[2]")).click();
		// Thread.sleep(3000);
		// driver.findElement(By.xpath("//*[text()='Ok']")).click();
		 Thread.sleep(3000);
			WebElement selectassignment=driver.findElement(By.xpath("//*[text()='Add New Assignment']"));
			JavascriptExecutor moveuptoassignment = (JavascriptExecutor) driver;
			moveuptoassignment.executeScript("arguments[0].scrollIntoView();", selectassignment);
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("//*[text()='Add New Assignment']")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@type='text'])[2]")).click();
		// Thread.sleep(3000);
		// driver.findElement(By.xpath("//*[text()='Ok']")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@role='checkbox'])[28]")).click();
		 Thread.sleep(3000);
		// driver.findElement(By.xpath("//*[text()='Save']")).click();
		 WebElement Clickonsavebutton= driver.findElement(By.xpath("//*[text()='Save']"));
			JavascriptExecutor moveuptosave = (JavascriptExecutor) driver;
			moveuptosave.executeScript("arguments[0].click();", Clickonsavebutton);
		 Thread.sleep(4000);
		 WebElement AddUpcbutton=driver.findElement(By.xpath("//*[text()='Add UPC not in DB']"));
			JavascriptExecutor moveuptoAddUPC = (JavascriptExecutor) driver;
			moveuptoAddUPC.executeScript("arguments[0].scrollIntoView();", AddUpcbutton);
			 Thread.sleep(3000);
			 driver.findElement(By.xpath("(//*[@name='create'])[2]")).click();
			 Thread.sleep(3000);
			// driver.findElement(By.xpath("//*[@class='mat-radio-outer-circle']")).click();
			 WebElement Clickonradiobutton= driver.findElement(By.xpath("//*[@class='mat-radio-outer-circle']"));
				JavascriptExecutor moveuptoradio = (JavascriptExecutor) driver;
				moveuptoradio.executeScript("arguments[0].click();", Clickonradiobutton);
			 Thread.sleep(3000);
			 driver.findElement(By.xpath("//*[text()='Update']")).click();
}
@Test(priority=11,enabled=true)
public void testCheckoutmodule() throws Exception
{
	Thread.sleep(5000);
	WebElement ClickCheckout= driver.findElement(By.xpath("//ion-button[text()=' Checkout']"));
	JavascriptExecutor clickanylocation = (JavascriptExecutor) driver;
	clickanylocation.executeScript("arguments[0].click();", ClickCheckout);
	Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[text()='more_vert'])[1]")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[text()='Edit'])[3]")).click();
	 Thread.sleep(4000);
	 driver.findElement(By.xpath("(//*[@type='number'])[7]")).clear();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@type='number'])[7]")).sendKeys("2");
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Update']")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@type='number'])[7]")).clear();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[@type='number'])[7]")).sendKeys("1");
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Update']")).click();
		Thread.sleep(3000);
		//driver.findElement(By.xpath("//ion-button[text()='Verify']")).click();
		WebElement Clickverify= driver.findElement(By.xpath("//ion-button[text()='Verify']"));
		JavascriptExecutor clickany = (JavascriptExecutor) driver;
		clickany.executeScript("arguments[0].click();", Clickverify);
		Thread.sleep(6000);
		driver.findElement(By.xpath("(//*[@name='arrow-round-forward'])[1]")).click(); 
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@name='arrow-round-forward'])[1]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@name='arrow-round-forward'])[1]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//ion-button[text()='Next']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Deliver the order to the customer']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@class='mat-tab-label-content'])[2]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@class='mat-tab-label-content'])[1]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[text()='Edit'])[3]")).click();
		Thread.sleep(3000);
		WebElement storesave=driver.findElement(By.xpath("(//*[text()='Update'])"));
		JavascriptExecutor moveuptoSavebutton = (JavascriptExecutor) driver;
		moveuptoSavebutton.executeScript("arguments[0].scrollIntoView();", storesave);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Address Line 1']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Address Line 1']")).sendKeys("Automation");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Address Line 2']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Address Line 2']")).sendKeys("Testing");
		Thread.sleep(3000);
/*		WebElement storesave=driver.findElement(By.xpath("//*[text()='Save']"));
		JavascriptExecutor moveuptoSavebutton = (JavascriptExecutor) driver;
		moveuptoSavebutton.executeScript("arguments[0].scrollIntoView();", storesave);  */
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='City']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='City']")).sendKeys("Integrationtesting");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='State']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='State']")).sendKeys(" Alabama ");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Phone']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Phone']")).sendKeys("1234567890");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Zip Code']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Zip Code']")).sendKeys("10003");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@role='checkbox'])[1]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@role='checkbox'])[1]")).click();
		Thread.sleep(3000);//*[text()='Save']
		driver.findElement(By.xpath("(//*[text()='Update'])")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()=' Integrationtesting ']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Credit Card']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Pay With Stripe']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Total']")).clear();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@placeholder='Total']")).sendKeys("150");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"card-element\"]/div/iframe")).sendKeys("4242 4242 4242 4242");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"card-element\"]/div/iframe")).sendKeys("02 / 25");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"card-element\"]/div/iframe")).sendKeys("584");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"card-element\"]/div/iframe")).sendKeys("10003",Keys.RETURN);
		Thread.sleep(3000);
		//driver.findElement(By.xpath("//*[text()='Pay Now']")).click();
	/*	WebElement ClickonPaynowbutton= driver.findElement(By.xpath("//*[text()='Pay Now']"));
		JavascriptExecutor moveuptoPosbutton = (JavascriptExecutor) driver;
		moveuptoPosbutton.executeScript("arguments[0].click();", ClickonPaynowbutton);  */
		WebElement storebalancedue=driver.findElement(By.xpath("//*[text()='Balance Due :']"));
		JavascriptExecutor moveuptobalancedue = (JavascriptExecutor) driver;
		moveuptobalancedue.executeScript("arguments[0].scrollIntoView();", storebalancedue);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Cash']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@type='number']")).sendKeys("10");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Ok']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Gift Card']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@type='number']")).sendKeys("15");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Ok']")).click();
		WebElement store2ndbalancedue=driver.findElement(By.xpath("//*[text()='Balance Due :']"));
		JavascriptExecutor moveupto2ndtimebalancedue = (JavascriptExecutor) driver;
		moveupto2ndtimebalancedue.executeScript("arguments[0].scrollIntoView();", store2ndbalancedue);
		Thread.sleep(3000);
		//driver.findElement(By.xpath("//*[text()='Close']")).click();
		WebElement Clickonclose= driver.findElement(By.xpath("//*[text()='Close']"));
		JavascriptExecutor moveuptoclosebutton = (JavascriptExecutor) driver;
		moveuptoclosebutton.executeScript("arguments[0].click();", Clickonclose);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Yes']")).click();
}
@Test(priority=12,enabled=true)
public void Addnewcustomer() throws Exception
{
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()='Start New Order']")).click();
	driver.findElement(By.xpath("//*[text()='Search For Customer']")).click();
	driver.findElement(By.xpath("//*[@id='form-group-input-1']")).sendKeys("sardar");
	driver.findElement(By.xpath("//*[@type='submit']")).click();
	Thread.sleep(3000);
	WebElement Clickonnewcustomer= driver.findElement(By.xpath("//*[text()='Add New Customer']"));
	JavascriptExecutor moveuptonewcustomer = (JavascriptExecutor) driver;
	moveuptonewcustomer.executeScript("arguments[0].click();", Clickonnewcustomer);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[@id='lastName']")).sendKeys("123");
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[@id='cellPhone']")).sendKeys("2345432112");
	Thread.sleep(3000);
	//driver.findElement(By.xpath("//*[text()='Add']")).click();
	WebElement Clickonaddbutton= driver.findElement(By.xpath("//*[text()='Add']"));
	JavascriptExecutor moveuptoaddbutton = (JavascriptExecutor) driver;
	moveuptoaddbutton.executeScript("arguments[0].click();", Clickonaddbutton);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Yes']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@name='search'])[2]")).sendKeys("client");
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[text()='search'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//*[text()=' Test client 1 ']")).click();
	Thread.sleep(3000);
	WebElement Clickonsavebutton= driver.findElement(By.xpath("//*[text()='Save']"));
	JavascriptExecutor moveuptosavebutton = (JavascriptExecutor) driver;
	moveuptosavebutton.executeScript("arguments[0].click();", Clickonsavebutton);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Yes']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-verify-organization/ion-content/ion-card[2]/ion-card-content/div/div[1]/ion-button")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Yes']")).click();
	Thread.sleep(3000);
    WebElement clickonaddshirt= driver.findElement(By.xpath("//*[text()='Add Shirt']"));
	JavascriptExecutor moveuptoaddshirt = (JavascriptExecutor) driver;
	moveuptoaddshirt.executeScript("arguments[0].click();", clickonaddshirt);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@class='mat-radio-container'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//*[@color='success'])[3]")).click();
	Thread.sleep(3000);
	 driver.findElement(By.xpath("(//*[text()=' + '])[1]")).click();
	 Thread.sleep(3000);
	 driver.findElement(By.xpath("//*[text()='Dropship to customer']")).click();
	 Thread.sleep(4000);
	 WebElement AddUpcbutton=driver.findElement(By.xpath("//*[text()='Add UPC not in DB']"));
		JavascriptExecutor moveuptoAddUPC = (JavascriptExecutor) driver;
		moveuptoAddUPC.executeScript("arguments[0].scrollIntoView();", AddUpcbutton);
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("(//*[@name='create'])[2]")).click();
		// Thread.sleep(3000);
		// driver.findElement(By.xpath("//*[@class='mat-radio-outer-circle']")).click();
		 Thread.sleep(3000);
		 driver.findElement(By.xpath("//*[text()='Update']")).click();
}
}
