package OperationsAppTasks;

import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.util.Properties;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.Test;

import com.pittsburgh.base.Baseclass;

public class Task1767ChromeMobileEmulatorItem1 
{
	public static WebDriver driver;
	public static Properties p1;
	@Test(priority=1, enabled=true)
	 public  void mobiletest() throws Exception{
//		  System.setProperty("webdriver.chrome.driver","./Lib/Browsers/chromedriver.exe");	
		Baseclass.setup();

			ChromeOptions options = new ChromeOptions();
			options.addArguments("--disable-notifications","--window-size=414,736");
			driver = new ChromeDriver(options);
			FileInputStream fis = new FileInputStream("./Lib/Properties/PropertyFile");
			p1 = new Properties();
			p1.load(fis);
			driver.get(p1.getProperty("URL"));
			options.setHeadless(true);
		//	driver.manage().window().maximize();
			driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			driver.findElement(By.xpath("//*[text()='Login']")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("//input[@placeholder='Email']")).sendKeys(p1.getProperty("Username"));
			driver.findElement(By.xpath("//input[@placeholder='Password']")).sendKeys(p1.getProperty("Password"));
			driver.findElement(By.xpath("//ion-button[@type='submit']")).click();
			//driver.findElement(By.xpath("//*[@id=\"mat-expansion-panel-header-5\"]/span[1]/mat-panel-title")).click();
			Thread.sleep(8000);
			driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-home/ion-header/ion-toolbar/ion-buttons[1]")).click();
			Thread.sleep(3000);
			WebElement element= driver.findElement(By.xpath("//*[text()=' POS ']"));
		      JavascriptExecutor js = (JavascriptExecutor) driver;
		      js.executeScript("arguments[0].click();", element);
		      Thread.sleep(3000);
			driver.findElement(By.xpath("//*[text()=' View ']")).click();
			driver.findElement(By.xpath("//*[@id='mat-dialog-0']/app-pos-view-screen/div/ion-button[3]")).click();
			Thread.sleep(3000);
			WebElement Okay=driver.findElement(By.xpath("//*[text()='Okay']"));
			boolean b=Okay.isDisplayed();
			System.out.println("Boolean  : "+b);
			if (b==true) {
				Okay.click();
				System.out.println("True________"+b+"______Clicked");
			}
			else {
				System.out.println("If failed");
			}
			WebElement PosName=driver.findElement(By.xpath("//*[@class=\'form-control ng-untouched ng-pristine ng-invalid\']"));
			PosName.click();
			PosName.sendKeys("sardar");
			driver.findElement(By.xpath("//*[@type='Submit']")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("//*[text()='Start New Order']")).click();
			driver.findElement(By.xpath("//*[text()='Search For Customer']")).click();
			driver.findElement(By.xpath("//*[@id='form-group-input-4']")).sendKeys("01132021");
			driver.findElement(By.xpath("//*[@type='submit']")).click();
			//driver.findElement(By.xpath("//*[text()='Matt ']")).click();
			WebElement Clickoncustomer= driver.findElement(By.xpath("//*[text()='Matt ']"));
		    JavascriptExecutor movematthewanywhere = (JavascriptExecutor) driver;
		    movematthewanywhere.executeScript("arguments[0].click();", Clickoncustomer);
			Thread.sleep(3000);
			driver.findElement(By.xpath("//ion-button[text()='Yes']")).click();
			Thread.sleep(3000);
		//	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-search-customer/ion-content/ion-card[3]/ion-card-content/table/tbody/tr/td[1]")).click();
			WebElement Clickonorganization= driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-search-customer/ion-content/ion-card[3]/ion-card-content/table/tbody/tr/td[1]"));
		    JavascriptExecutor moveorganywhere = (JavascriptExecutor) driver;
		    moveorganywhere.executeScript("arguments[0].click();", Clickonorganization);
			Thread.sleep(5000);
			driver.findElement(By.xpath("//*[text()='Yes']")).click();
			Thread.sleep(3000);
		//	driver.findElement(By.xpath("//*[text()='Skip']")).click();
			Thread.sleep(3000);
			WebElement Clickonskip= driver.findElement(By.xpath("//*[text()='Skip']"));
		    JavascriptExecutor moveskipwanywhere = (JavascriptExecutor) driver;
		    moveskipwanywhere.executeScript("arguments[0].click();", Clickonskip);
			Thread.sleep(3000);
		//	driver.findElement(By.xpath("//*[text()='Agency Order ']")).click();
			WebElement ClickonAgencyorder= driver.findElement(By.xpath("//*[text()='Agency Order ']"));
		    JavascriptExecutor moveagencywanywhere = (JavascriptExecutor) driver;
		    moveagencywanywhere.executeScript("arguments[0].click();", ClickonAgencyorder);
			Thread.sleep(3000);
			driver.findElement(By.xpath("//*[text()='OK']")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("(//ion-icon[@aria-label='create'])[4]")).click();
			Thread.sleep(3000);
			driver.findElement(By.xpath("//ion-button[text()='Neville Island']")).click();
			driver.findElement(By.xpath("//*[text()='Pick BIN Label ']")).click();
			Thread.sleep(3000); //div[text()='70234613 Apr 1, 2021']
			WebElement addproduct2= driver.findElement(By.xpath("//*[text()='Microsoft Print to PDF']"));
		    JavascriptExecutor jsee2 = (JavascriptExecutor) driver;
		    jsee2.executeScript("arguments[0].click();", addproduct2);
		    Thread.sleep(3000);
		    driver.findElement(By.xpath("//*[text()='Print ']")).click();
		    Thread.sleep(3000);
		    WebElement hiddenDivtag = driver.findElement(By.xpath("//span[@name='pickBinLabel']"));
		  	String nnn = hiddenDivtag.getText(); // does not work (returns "" as expected)
		  	String scripttt = "return arguments[0].innerText";
		  	nnn= (String) ((JavascriptExecutor) driver).executeScript(scripttt, hiddenDivtag);
		  	System.out.println(nnn);
		  	Thread.sleep(3000);
			WebElement addproduct= driver.findElement(By.xpath("//*[contains(text(),'Add Product ')]"));
		     JavascriptExecutor jsee = (JavascriptExecutor) driver;
		     jsee.executeScript("arguments[0].click();", addproduct);
		     Thread.sleep(3000);
		     driver.findElement(By.xpath("//*[text()='Search Product to Add']")).click();
		     Thread.sleep(3000);
		     driver.findElement(By.xpath("(//input[@type='text'])[7]")).click();
		     Thread.sleep(3000);
		     driver.findElement(By.xpath("//span[text()=' Blauer ']")).click();
		     driver.findElement(By.xpath("//*[@formcontrolname='manufacturerNum']")).click();
		     driver.findElement(By.xpath("//span[text()=' 8600-Z ']")).click();
		     //  driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();
		     WebElement Clickonsearch= driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]"));
			 JavascriptExecutor movesearchanywhere = (JavascriptExecutor) driver;
			 movesearchanywhere.executeScript("arguments[0].click();", Clickonsearch);
		     Thread.sleep(3000);
		      // driver.findElement(By.xpath("//td[text()=' LS ZIPPERED POLYESTER SHIRT ']")).click();
		     WebElement Click2ndpolyster= driver.findElement(By.xpath("//td[text()=' LS ZIPPERED POLYESTER SHIRT ']"));
			 JavascriptExecutor move2ndpolysteranywhere = (JavascriptExecutor) driver;
			 move2ndpolysteranywhere.executeScript("arguments[0].click();", Click2ndpolyster);
		     Thread.sleep(3000);
		     driver.findElement(By.xpath("(//ion-button[text()='Show Related '])[2]")).click();
		     Thread.sleep(3000);  
		//	driver.findElement(By.xpath("//td[text()=' BLACK ']")).click();
		     WebElement Clickblockcolour= driver.findElement(By.xpath("//td[text()=' BLACK ']"));
			 JavascriptExecutor moveblockanywhere = (JavascriptExecutor) driver;
			 moveblockanywhere.executeScript("arguments[0].click();", Clickblockcolour);
			 Thread.sleep(3000);
			 driver.findElement(By.xpath("//*[text()=' Add product to Order']")).click();
			 Thread.sleep(3000);
			 driver.findElement(By.xpath("(//div[@class='mat-radio-container'])[1]")).click();
			 Thread.sleep(3000);
			 // driver.findElement(By.xpath("(//div[@class='mat-radio-container'])[3]")).click();
			 WebElement Clickpickedbutton= driver.findElement(By.xpath("(//div[@class='mat-radio-container'])[3]"));
			 JavascriptExecutor movepickedbuttonanywhere = (JavascriptExecutor) driver;
			  movepickedbuttonanywhere.executeScript("arguments[0].click();", Clickpickedbutton);
			  Thread.sleep(3000);
				WebElement addproduct5= driver.findElement(By.xpath("//ion-button[text()='Use Other Printer']"));
			      JavascriptExecutor jsee5 = (JavascriptExecutor) driver;
			      jsee5.executeScript("arguments[0].click();", addproduct5);
				Thread.sleep(3000);
				  WebElement addproduct4= driver.findElement(By.xpath("//*[text()='Microsoft Print to PDF']"));
			      JavascriptExecutor jsee4 = (JavascriptExecutor) driver;
			      jsee4.executeScript("arguments[0].click();", addproduct4);	
				Thread.sleep(3000);
			  WebElement addproduct3= driver.findElement(By.xpath("(//*[@color='success'])[6]"));
		      JavascriptExecutor jsee3 = (JavascriptExecutor) driver;
		      jsee3.executeScript("arguments[0].click();", addproduct3);   
            Thread.sleep(3000);
WebElement hiddenDiv = driver.findElement(By.xpath("//span[@name='ppssBarcode']"));
String n = hiddenDiv.getText(); // does not work (returns "" as expected)
String script = "return arguments[0].innerText";
n= (String) ((JavascriptExecutor) driver).executeScript(script, hiddenDiv);
System.out.println(n);
driver.findElement(By.xpath("//input[@name='upc']")).sendKeys(n);
Thread.sleep(3000);
driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@name='upc']")).sendKeys(nnn);
Thread.sleep(3000);
driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();  
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Save']")).click(); 
Thread.sleep(5000);
WebElement ClickCheckout= driver.findElement(By.xpath("//ion-button[text()=' Checkout']"));
JavascriptExecutor clickanylocation = (JavascriptExecutor) driver;
clickanylocation.executeScript("arguments[0].click();", ClickCheckout);
Thread.sleep(3000);
//driver.findElement(By.xpath("//ion-button[text()='Verify']")).click();
WebElement Clickverify= driver.findElement(By.xpath("//ion-button[text()='Verify']"));
JavascriptExecutor clickany = (JavascriptExecutor) driver;
clickany.executeScript("arguments[0].click();", Clickverify);
Thread.sleep(10000);
driver.findElement(By.xpath("//ion-button[text()='Next']")).click(); 
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Customer will pickup the order']")).click(); 
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Neville Island Store']")).click(); 
Thread.sleep(6000);
driver.findElement(By.xpath("//ion-button[text()='Agency Bill']")).click(); 
Thread.sleep(3000);
driver.findElement(By.xpath("(//input[@type='text'])[7]")).sendKeys("12345");
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Save']")).click(); 
Thread.sleep(10000);
driver.findElement(By.xpath("//ion-button[text()='back']")).click();    
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Exit POS Mode']")).click();
}
@Test(priority=2,enabled=true)
public void Releaseorder() throws Exception
{
	Thread.sleep(5000);
	WebElement Clickorderneedsreviewed= driver.findElement(By.xpath("//div[text()='Orders Need Reviewed']"));
	JavascriptExecutor moveneedsreviewedanywhre = (JavascriptExecutor) driver;
	moveneedsreviewedanywhre.executeScript("arguments[0].click();", Clickorderneedsreviewed);
	Thread.sleep(3000);
	//driver.findElement(By.xpath("(//tr[@class='mat-row ng-star-inserted'])[1]")).click();
	WebElement Clickoncreatedorder= driver.findElement(By.xpath("(//tr[@class='mat-row ng-star-inserted'])[1]"));
	JavascriptExecutor movenewcreatedorder = (JavascriptExecutor) driver;
	movenewcreatedorder.executeScript("arguments[0].click();", Clickoncreatedorder);
	Thread.sleep(3000);
	//	driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[1]")).click();
	WebElement Clickonfirstbox= driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[1]"));
	JavascriptExecutor moveuotofirstbox = (JavascriptExecutor) driver;
	moveuotofirstbox.executeScript("arguments[0].click();", Clickonfirstbox);
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[2]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[3]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[4]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//div[@class='mat-checkbox-inner-container'])[5]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//ion-button[text()='RELEASE ORDER']")).click();
		Thread.sleep(10000);
		driver.findElement(By.xpath("//span[text()='OK']")).click();
}
@Test(priority=3,enabled=true)
public void Processorder() throws Exception {
Thread.sleep(5000);
driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-orders-need-reviewed/ion-header/ion-toolbar/ion-buttons[1]")).click();
/*WebElement Clickonmenubutton= driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-orders-need-reviewed/ion-header/ion-toolbar/ion-buttons[1]"));
JavascriptExecutor moveuptomenubutton = (JavascriptExecutor) driver;
moveuptomenubutton.executeScript("arguments[0].click();", Clickonmenubutton);  */
Thread.sleep(2000);
driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-orders-need-reviewed/ion-header/ion-toolbar/ion-buttons[1]")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//mat-panel-title[text()=' Home ']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-label[text()=' Home ']")).click();
Thread.sleep(3000);
//driver.findElement(By.xpath("//div[text()='Pick Bins Need Processed']")).click(); 
WebElement Clickonpicbinneedsreviewed= driver.findElement(By.xpath("//div[text()='Pick Bins Need Processed']"));
JavascriptExecutor movepicbinbinneedsreviewed = (JavascriptExecutor) driver;
movepicbinbinneedsreviewed.executeScript("arguments[0].click();", Clickonpicbinneedsreviewed);
Thread.sleep(3000);    
WebElement element2= driver.findElement(By.xpath("(//tr[@class='mat-row ng-star-inserted'])[1]"));
JavascriptExecutor js2 = (JavascriptExecutor) driver;
js2.executeScript("arguments[0].click();", element2);
Thread.sleep(3000);
driver.findElement(By.xpath("//span[text()='View Pick Bin']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Scan']")).click();
Thread.sleep(3000);
WebElement picbinbarcode = driver.findElement(By.xpath("//li[@class='ng-star-inserted']"));
String storeinstring = picbinbarcode.getText(); // does not work (returns "" as expected)
String getinnerscript = "return arguments[0].innerText";
storeinstring= (String) ((JavascriptExecutor) driver).executeScript(getinnerscript, picbinbarcode);
System.out.println(getinnerscript);
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys(storeinstring);
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Search']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Next']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Next']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@type='number']")).clear();
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@type='number']")).sendKeys("1");
Thread.sleep(3000);    
driver.findElement(By.xpath("//ion-button[text()='Print']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Next']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Scan Container Barcode']")).click();
Thread.sleep(3000);
WebElement Storecontainerbarcode = driver.findElement(By.xpath("//span[@name='containerLabelBarcode']"));
String getcontainerbarcode = Storecontainerbarcode.getText(); // does not work (returns "" as expected)
String getinnertext = "return arguments[0].innerText";
getcontainerbarcode= (String) ((JavascriptExecutor) driver).executeScript(getinnertext, Storecontainerbarcode);
System.out.println(getcontainerbarcode);
driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys(getcontainerbarcode);
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Search']")).click();
Thread.sleep(3000);
 // driver.findElement(By.xpath("//ion-button[text()='Scan']")).click();
WebElement clickonsearchbutton= driver.findElement(By.xpath("//ion-button[text()='Scan']"));
JavascriptExecutor moveuptosearchbutton = (JavascriptExecutor) driver;
moveuptosearchbutton.executeScript("arguments[0].click();", clickonsearchbutton);
Thread.sleep(3000);
WebElement Storeppssbarcode1 = driver.findElement(By.xpath("(//div[@class='ng-star-inserted'])[2]"));
String getppssbarcode1 = Storeppssbarcode1.getText(); // does not work (returns "" as expected)
String getinnertextppss1 = "return arguments[0].innerText";
getppssbarcode1= (String) ((JavascriptExecutor) driver).executeScript(getinnertextppss1, Storeppssbarcode1);
Thread.sleep(3000);
/*WebElement Enterppssbarcodenum= driver.findElement(By.xpath("//input[@placeholder='UPC']"));
JavascriptExecutor moveuptoppssbarcodenum = (JavascriptExecutor) driver;
moveuptoppssbarcodenum.executeScript("arguments[0].click();", Enterppssbarcodenum); */
//driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys(getppssbarcode1);
JavascriptExecutor js = (JavascriptExecutor) driver;
WebElement w1=driver.findElement(By.xpath("//input[@placeholder='UPC']"));
js.executeScript("arguments[0].scrollIntoView();", w1);
Thread.sleep(2000);
driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys(getppssbarcode1);
Thread.sleep(3000);
//driver.findElement(By.xpath("//ion-button[text()='Search']")).click();
WebElement clickonsearchbutton2= driver.findElement(By.xpath("//ion-button[text()='Search']"));
JavascriptExecutor moveuptosearchbutton2 = (JavascriptExecutor) driver;
moveuptosearchbutton2.executeScript("arguments[0].click();", clickonsearchbutton2);
Thread.sleep(3000);
driver.findElement(By.xpath("//span[text()='Okay']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Scan Container ']")).click();
Thread.sleep(3000);
WebElement Storecontainerbarcode2 = driver.findElement(By.xpath("//span[@name='containerLabelBarcode']"));
String getcontainerbarcode2 = Storecontainerbarcode2.getText(); // does not work (returns "" as expected)
String getinnertextcontainer2 = "return arguments[0].innerText";
getcontainerbarcode2= (String) ((JavascriptExecutor) driver).executeScript(getinnertextcontainer2, Storecontainerbarcode2);
System.out.println(getcontainerbarcode2);
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys(getcontainerbarcode2);
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Search']")).click();
driver.findElement(By.xpath("//ion-button[text()='Scan Slot ']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys("SL000000002");
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Search']")).click();
Thread.sleep(3000);
driver.findElement(By.xpath("//ion-button[text()='Finish']")).click(); 
Thread.sleep(10000);
driver.findElement(By.xpath("//span[text()='Okay']")).click();
}
@Test(priority=4,enabled=true)
public void Transfertocontainer() throws Exception
{
	Thread.sleep(5000);
	WebElement clickbackarrow1time= driver.findElement(By.xpath("//button[@class='button-native sc-ion-back-button-md']"));
	JavascriptExecutor movebackarrow1time = (JavascriptExecutor) driver;
	movebackarrow1time.executeScript("arguments[0].click();", clickbackarrow1time);
	Thread.sleep(3000);
	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-home/ion-header/ion-toolbar/ion-buttons[1]")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("//mat-panel-title[text()=' Orders ']")).click(); 
	WebElement clickordersmodule= driver.findElement(By.xpath("//mat-panel-title[text()=' Orders ']"));
	JavascriptExecutor moveuptoordersmodule = (JavascriptExecutor) driver;
	moveuptoordersmodule.executeScript("arguments[0].click();", clickordersmodule);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-label[text()=' View Orders ']")).click(); 
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[1]")).click(); 
	Thread.sleep(4000);
	//driver.findElement(By.xpath("//strong[text()='Pick Bins & Container Tracking ']")).click(); 
	WebElement selectpicbincontainer= driver.findElement(By.xpath("//strong[text()='Pick Bins & Container Tracking ']"));
	JavascriptExecutor moveuptopicbincontainer = (JavascriptExecutor) driver;
	moveuptopicbincontainer.executeScript("arguments[0].click();", selectpicbincontainer);
	Thread.sleep(3000);
//	driver.findElement(By.xpath("(//img[@src='./assets/images/back-arrow.png'])[1]")).click(); 
	WebElement clickarrow= driver.findElement(By.xpath("(//img[@src='./assets/images/back-arrow.png'])[1]"));
	JavascriptExecutor clickbelowarrow = (JavascriptExecutor) driver;
	clickbelowarrow.executeScript("arguments[0].click();", clickarrow);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()=' TRANSFER ']")).click(); 	
	Thread.sleep(3000);
/*	WebElement containerbarcode = driver.findElement(By.xpath("(//div[@class='col-9'])[2]"));
  	String storecontainerbarcode = containerbarcode.getText(); // does not work (returns "" as expected)
  	String getinnercontainerbarcode = "return arguments[0].innerText";
  	storecontainerbarcode= (String) ((JavascriptExecutor) driver).executeScript(getinnercontainerbarcode, containerbarcode);
  	System.out.println(getinnercontainerbarcode); 
	Thread.sleep(3000);                               */
	driver.findElement(By.xpath("//ion-button[text()=' SCAN ']")).click(); 
	Thread.sleep(3000);
	driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys("SL000000006"); 
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click(); 
 	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()=' COMPLETE ']")).click(); 
	Thread.sleep(5000);
	driver.findElement(By.xpath("(//button[@class='button-native sc-ion-back-button-md'])[2]")).click(); 
	Thread.sleep(3000);
	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-order-details/ion-header/ion-toolbar/ion-buttons/ion-menu-button")).click();
	Thread.sleep(5000);
	driver.findElement(By.xpath("//mat-panel-title[text()=' Dashboards ']")).click();
}
@Test(priority=5,enabled=true)
public void Tailoring() throws Exception
{
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-label[text()=' Tailoring ']")).click();
	Thread.sleep(4000);
	driver.findElement(By.xpath("//ion-button[text()='Available work']")).click();
	Thread.sleep(4000);
	driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[11]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//span[text()='Assign to Me']")).click();
	Thread.sleep(5000);
	driver.findElement(By.xpath("//ion-button[text()='All work']")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("//ion-icon[@name='options']")).click();
	 WebElement clickonsortingoptions= driver.findElement(By.xpath("(//ion-icon[@name='options'])[3]"));
		JavascriptExecutor moveuptosortingoptionsicon = (JavascriptExecutor) driver;
		moveuptosortingoptionsicon.executeScript("arguments[0].click();", clickonsortingoptions);
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//ion-icon[@name='swap'])[2]")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//ion-radio[@name='packagingBarcode']")).click();
		Thread.sleep(3000);
		//driver.findElement(By.xpath("//ion-toggle[@role='checkbox']")).click();
		WebElement clickondecendingbox= driver.findElement(By.xpath("(//ion-toggle[@role='checkbox'])[2]"));
		JavascriptExecutor moveuptodecendingbox = (JavascriptExecutor) driver;
		moveuptodecendingbox.executeScript("arguments[0].click();", clickondecendingbox);
		Thread.sleep(3000);
		//driver.findElement(By.xpath("//span[text()='Assign to Me']")).click();
		WebElement clickonsortbutton= driver.findElement(By.xpath("(//ion-button[text()='SORT'])[2]"));
		JavascriptExecutor moveuptosortbutton = (JavascriptExecutor) driver;
		moveuptosortbutton.executeScript("arguments[0].click();", clickonsortbutton);
	Thread.sleep(3000);
     driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[13]")).click();
 	Thread.sleep(3000);
    driver.findElement(By.xpath("//span[text()='View Details']")).click();
    Thread.sleep(3000);
//	driver.findElement(By.xpath("(//div[text()='LS ZIPPERED POLYESTER SHIRT'])[2]")).click();
    WebElement clickonpolystershirt= driver.findElement(By.xpath("(//div[text()='LS ZIPPERED POLYESTER SHIRT'])[2]"));
	JavascriptExecutor moveuptoploystershirt = (JavascriptExecutor) driver;
	moveuptoploystershirt.executeScript("arguments[0].click();", clickonpolystershirt);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Begin']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Complete']")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-tailoring-item-detail/ion-header/ion-toolbar/ion-buttons/ion-back-button/button/span/ion-icon")).click();
	WebElement clickbackarrow3rdtime= driver.findElement(By.xpath("(//button[@class='button-native sc-ion-back-button-md'])[3]"));
	JavascriptExecutor movebackarrow3rdtime = (JavascriptExecutor) driver;
	movebackarrow3rdtime.executeScript("arguments[0].click();", clickbackarrow3rdtime);
	Thread.sleep(3000);
	WebElement clickTransferbutton= driver.findElement(By.xpath("//ion-button[text()='TRANSFER']"));
	JavascriptExecutor moveuptotransferbutton = (JavascriptExecutor) driver;
	moveuptotransferbutton.executeScript("arguments[0].click();", clickTransferbutton);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Scan']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys("SL000000010");
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();
	Thread.sleep(5000);
	driver.findElement(By.xpath("//ion-button[text()='Complete']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//button[@class='button-native sc-ion-back-button-md'])[2]")).click();
	//Thread.sleep(5000);
	//driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[42]")).click();
/*	WebElement clicknewtransferorder= driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[44]"));
	JavascriptExecutor moveuptonewtransferorder = (JavascriptExecutor) driver;
	moveuptonewtransferorder.executeScript("arguments[0].click();", clicknewtransferorder);  */
//	JavascriptExecutor scrolldownuptolast = (JavascriptExecutor) driver;
/*	WebElement Storelastelement=driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-167']"));
	JavascriptExecutor scrolldownuptolast = (JavascriptExecutor) driver;
	scrolldownuptolast.executeScript("arguments[0].scrollIntoView();", Storelastelement);  
	Storelastelement.getText();                                  */
/*	Robot robot = new Robot();
	robot.keyPress(KeyEvent.VK_PAGE_DOWN);
	robot.keyRelease(KeyEvent.VK_PAGE_DOWN);
	JavascriptExecutor js = ((JavascriptExecutor) driver);
	js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
	Thread.sleep(3000);
	WebElement clicknewtransferorder= driver.findElement(By.xpath("//*[@id=\"mat-expansion-panel-header-166\"]"));
	JavascriptExecutor moveuptonewtransferorder = (JavascriptExecutor) driver;
	moveuptonewtransferorder.executeScript("arguments[0].click();", clicknewtransferorder);
	//Thread.sleep(5000);
	Thread.sleep(2000);
 driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[59]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//div[text()='LS ZIPPERED POLYESTER SHIRT'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Begin']")).click();
//	Thread.sleep(5000);
//	driver.findElement(By.xpath("(//div[text()='LS ZIPPERED POLYESTER SHIRT'])[2]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Complete']")).click();
	Thread.sleep(5000);
//	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-tailoring-item-detail/ion-header/ion-toolbar/ion-buttons/ion-back-button/button/span/ion-icon")).click();
	WebElement clickbackarrow3rdtime= driver.findElement(By.xpath("(//button[@class='button-native sc-ion-back-button-md'])[3]"));
	JavascriptExecutor movebackarrow3rdtime = (JavascriptExecutor) driver;
	movebackarrow3rdtime.executeScript("arguments[0].click();", clickbackarrow3rdtime);
	Thread.sleep(3000);
//	driver.findElement(By.xpath("//ion-button[text()='TRANSFER']")).click();
	WebElement clickTransferbutton= driver.findElement(By.xpath("//ion-button[text()='TRANSFER']"));
	JavascriptExecutor moveuptotransferbutton = (JavascriptExecutor) driver;
	moveuptotransferbutton.executeScript("arguments[0].click();", clickTransferbutton);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Scan']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//input[@placeholder='UPC']")).sendKeys("SL000000010");
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='Search'])[2]")).click();
	Thread.sleep(5000);
	driver.findElement(By.xpath("//ion-button[text()='Complete']")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//button[@class='button-native sc-ion-back-button-md'])[2]")).click();    */
}
@Test(priority=6,enabled=true)
public void QualityAsurance() throws Exception
{
	Thread.sleep(5000);
	driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-tailoring/ion-header/ion-toolbar/ion-buttons[1]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("//mat-panel-title[text()=' Dashboards ']")).click();
	Thread.sleep(5000);
	WebElement clickQA= driver.findElement(By.xpath("//ion-label[text()=' Quality Assurance ']"));
	JavascriptExecutor clickanywhere = (JavascriptExecutor) driver;
	clickanywhere.executeScript("arguments[0].click();", clickQA);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-button[text()='All work'])[2]")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("(//ion-icon[@name='options'])[4]")).click();
	 WebElement clickonsortingoptions= driver.findElement(By.xpath("(//ion-icon[@name='options'])[4]"));
		JavascriptExecutor moveuptosortingoptionsicon = (JavascriptExecutor) driver;
		moveuptosortingoptionsicon.executeScript("arguments[0].click();", clickonsortingoptions);
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-icon[@name='swap'])[3]")).click();
	Thread.sleep(3000);
	driver.findElement(By.xpath("(//ion-radio[@name='packagingBarcode'])[2]")).click();
	Thread.sleep(3000);
	//driver.findElement(By.xpath("(//ion-toggle[@role='checkbox'])[3]")).click();
	WebElement clickondecendingbox= driver.findElement(By.xpath("(//ion-toggle[@role='checkbox'])[3]"));
	JavascriptExecutor moveuptodecendingbox = (JavascriptExecutor) driver;
	moveuptodecendingbox.executeScript("arguments[0].click();", clickondecendingbox);
	Thread.sleep(3000);
	//driver.findElement(By.xpath("(//ion-button[text()='SORT'])[3]")).click();
	WebElement clickonsortbutton= driver.findElement(By.xpath("(//ion-button[text()='SORT'])[3]"));
	JavascriptExecutor moveuptosortbutton = (JavascriptExecutor) driver;
	moveuptosortbutton.executeScript("arguments[0].click();", clickonsortbutton);
	Thread.sleep(3000);
    driver.findElement(By.xpath("(//ion-icon[@name='arrow-forward'])[33]")).click();
    Thread.sleep(3000);
    driver.findElement(By.xpath("//span[text()='View Details']")).click();
    Thread.sleep(3000);
	driver.findElement(By.xpath("(//div[text()='LS ZIPPERED POLYESTER SHIRT'])[2]")).click();
	Thread.sleep(6000);
	driver.findElement(By.xpath("//ion-button[text()='Yes']")).click(); 
	Thread.sleep(3000);
	//driver.findElement(By.xpath("//ion-button[text()='Yes']")).click(); 
	WebElement clickonyesbutton= driver.findElement(By.xpath("//ion-button[text()='Yes']"));
	JavascriptExecutor moveuptoyesbutton = (JavascriptExecutor) driver;
	moveuptoyesbutton.executeScript("arguments[0].click();", clickonyesbutton);
	Thread.sleep(3000);
	//driver.findElement(By.xpath("(//ion-button[text()='Pass'])[1]")).click();
	WebElement clickonpassbutton= driver.findElement(By.xpath("(//ion-button[text()='Pass'])[1]"));
	JavascriptExecutor moveuptopassbutton = (JavascriptExecutor) driver;
	moveuptopassbutton.executeScript("arguments[0].click();", clickonpassbutton);
	Thread.sleep(3000);
	JavascriptExecutor moveuptotakepicture = (JavascriptExecutor) driver;
	WebElement StoreTakepicture=driver.findElement(By.xpath("//ion-button[text()='Take Picture']"));
	moveuptotakepicture.executeScript("arguments[0].scrollIntoView();", StoreTakepicture);
	Thread.sleep(3000);
	driver.findElement(By.xpath("//ion-button[text()='Take Picture']")).click();
	Thread.sleep(2000);
	StringSelection ss = new StringSelection(System.getProperty("fileToUpload"));
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);
    Robot robot = new Robot();
    Thread.sleep(2000);
    robot.keyPress(KeyEvent.VK_ENTER);
    robot.keyRelease(KeyEvent.VK_ENTER);
    robot.keyPress(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_V);
    robot.keyRelease(KeyEvent.VK_V);
    robot.keyRelease(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_ENTER);
    Thread.sleep(2000);
    robot.keyRelease(KeyEvent.VK_ENTER);
	Thread.sleep(3000);
	WebElement Clickcomplete= driver.findElement(By.xpath("//ion-button[text()='QC Complete']"));
	JavascriptExecutor Clickanyloc = (JavascriptExecutor) driver;
	Clickanyloc.executeScript("arguments[0].click();", Clickcomplete);  
//	driver.findElement(By.xpath("//ion-button[text()='QC Complete']")).click();
}
}